#!/bin/sh
# Check if this is the initial commit
if [[ $(git rev-parse --verify HEAD >/dev/null 2>&1) ]]
then
	echo "pre-commit: About to create a new commit..."
	against=HEAD
else
	echo "pre-commit: About to create the first commit..."
	against=4b825dc642cb6eb9a060e54bf8d69288fbee4904
fi

# Use git diff-index to check for whitespace errors
echo "pre-commit: Testing for forgotten prints..."
PRINTS=$( git diff-index HEAD -S "println" --pickaxe-all )
if [[ $PRINTS  ]]
then
	echo $PRINTS
	echo "pre-commit: Please remove prints from your patch"
	exit 1
fi
